# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20181024_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=50)),
                ('address_company', models.CharField(max_length=250)),
                ('country_company', django_countries.fields.CountryField(max_length=2)),
                ('email_company', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Company'),
        ),
    ]
